# Generated by Django 4.1.3 on 2023-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_man', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory_man.inventoryitem',),
        ),
    ]
